# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_first_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('add_librarian', 'Регистрация библиотекаря'), ('add_reader', 'Регистрация читателя')), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='edit_request',
            field=models.BooleanField(default=False, verbose_name='edit_request'),
        ),
    ]
