# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170511_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('add_librarian', 'add_librarian'), ('add_book', 'add_book'), ('cancellation_book', 'cancellation_book'), ('add_reader', 'add_reader')), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
