# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170511_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=150, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='self_number',
            field=models.CharField(blank=True, max_length=150, verbose_name='self_number'),
        ),
        migrations.AddField(
            model_name='user',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=150, verbose_name='ticket_number'),
        ),
    ]
