# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 14:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('elcat', '0004_library_city'),
        ('accounts', '0009_user_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2017, 5, 20, 14, 25, 2, 656428, tzinfo=utc), verbose_name='Дата и время создания')),
                ('closed', models.BooleanField(default=False, verbose_name='Заказ закрыт')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elcat.book', verbose_name='книга')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Читатель')),
            ],
        ),
        migrations.CreateModel(
            name='IssuedBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime(2017, 5, 20, 14, 25, 2, 654423, tzinfo=utc))),
                ('prolong_request', models.BooleanField(default=False, verbose_name='Запрошено продление')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elcat.book', verbose_name='Книга')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Читатель')),
            ],
        ),
    ]
