# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 15:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_bookorder_issuedbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 20, 15, 5, 57, 374894, tzinfo=utc), verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='issuedbooks',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 20, 15, 5, 57, 373426, tzinfo=utc)),
        ),
    ]
