# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 19:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170520_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 20, 19, 53, 39, 421261, tzinfo=utc), verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='issuedbooks',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 20, 19, 53, 39, 419168, tzinfo=utc)),
        ),
    ]
