# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 12:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20170520_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReminderRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=150, verbose_name='Токен')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заброс на сброс пароля',
                'verbose_name_plural': 'Запросы на срос пароля',
            },
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='issuedbooks',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
