# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('author_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='bbk1',
            fields=[
                ('bbk1_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code1', models.CharField(max_length=30)),
                ('description1', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='bbk2',
            fields=[
                ('bbk2_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code2', models.CharField(max_length=30)),
                ('description2', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('book_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('inventory', models.IntegerField(null=True)),
                ('volume', models.CharField(max_length=50, null=True)),
                ('bookauthor_id', models.BigIntegerField()),
                ('isbn', models.CharField(max_length=20, null=True)),
                ('isbn10', models.CharField(max_length=20, null=True)),
                ('year', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('price', models.FloatField()),
                ('isdeleted', models.BooleanField(default=False)),
                ('author_id', models.ManyToManyField(to='elcat.author')),
                ('bbk1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elcat.bbk1')),
                ('bbk2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elcat.bbk2')),
            ],
        ),
        migrations.CreateModel(
            name='booksatlibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booksfromok', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='bookstotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booksfromok', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('content_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('genre_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='language',
            fields=[
                ('language_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='library',
            fields=[
                ('library_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='librarytown',
            fields=[
                ('librarytown_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('town', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='publisher',
            fields=[
                ('publisher_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='series',
            fields=[
                ('series_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='shelfplace',
            fields=[
                ('shelfplace_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='booksatlibrary',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elcat.library'),
        ),
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elcat.content'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elcat.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elcat.language'),
        ),
        migrations.AddField(
            model_name='book',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elcat.library'),
        ),
        migrations.AddField(
            model_name='book',
            name='librarytown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elcat.librarytown'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elcat.publisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elcat.series'),
        ),
        migrations.AddField(
            model_name='book',
            name='shelfplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elcat.shelfplace'),
        ),
    ]
