# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elcat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='text',
        ),
    ]
