# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elcat', '0004_library_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='librarytown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elcat.librarytown'),
        ),
    ]
