# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0002_message_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=150, verbose_name='Тема'),
        ),
    ]
