# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0005_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='system_context',
            field=models.CharField(blank=True, max_length=150, verbose_name='Системный контекст'),
        ),
    ]
